name: Daily Industrial Automation Newsletter

on:
  schedule:
    - cron: '0 3 * * *'   # Runs at 3 AM UTC = 9 AM IST daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run newsletter script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python -c "
import os
with open('send_newsletter.py') as f:
    code = f.read()
code = code.replace('bcityfelirupkdow', os.environ['EMAIL_PASSWORD'])
exec(code)
"
